In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [5]:
import pandas as pd
import numpy as np


In [6]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
df['target'] = dataset.target

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
df_copy = df[df['target'] != 2]

In [15]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [22]:
##independent and dependent feature
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
##train test spilit
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [25]:
clasiffier = LogisticRegression()

In [26]:
##train
clasiffier.fit(X_train, y_train)

LogisticRegression()

In [33]:
clasiffier.predict_proba(X_test)

array([[0.00144397, 0.99855603],
       [0.01745215, 0.98254785],
       [0.00359633, 0.99640367],
       [0.96426787, 0.03573213],
       [0.93474767, 0.06525233],
       [0.96669519, 0.03330481],
       [0.99197521, 0.00802479],
       [0.03413528, 0.96586472],
       [0.97021318, 0.02978682],
       [0.97500261, 0.02499739],
       [0.94874463, 0.05125537],
       [0.95431635, 0.04568365],
       [0.00502564, 0.99497436],
       [0.98309085, 0.01690915],
       [0.01045247, 0.98954753],
       [0.97787998, 0.02212002],
       [0.00251112, 0.99748888],
       [0.00154214, 0.99845786],
       [0.96994373, 0.03005627],
       [0.95517443, 0.04482557],
       [0.00835383, 0.99164617],
       [0.02377754, 0.97622246],
       [0.95342874, 0.04657126],
       [0.98084186, 0.01915814],
       [0.0288064 , 0.9711936 ],
       [0.97695936, 0.02304064],
       [0.97877889, 0.02122111],
       [0.01705948, 0.98294052],
       [0.96439212, 0.03560788],
       [0.0018038 , 0.9981962 ],
       [0.

In [27]:
##prediction
y_pred = clasiffier.predict(X_test)

In [28]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [30]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
55    1
88    1
26    0
42    0
69    1
15    0
40    0
96    1
9     0
72    1
11    0
47    0
85    1
Name: target, dtype: int64

In [29]:
##confusion matrix,accuracy score,classification report :
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [31]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [34]:
##hyperparameter tunning:

##1) gridsearchcv:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')


In [35]:
parameters = {'penalty':('l1','l2','lasticnet',None),'C' : [1,10,20],'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga')}

In [37]:
clf = GridSearchCV(clasiffier,param_grid = parameters,cv=5)

In [38]:
##train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'lasticnet', None),
                         'solver': ('newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga')})

In [39]:
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [40]:
classifier = LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [41]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [42]:
y_pred = classifier.predict(X_test)

In [43]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
55    1
88    1
26    0
42    0
69    1
15    0
40    0
96    1
9     0
72    1
11    0
47    0
85    1
Name: target, dtype: int64

In [44]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [45]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [46]:
##Randomised SearchCv:
from sklearn.model_selection import RandomizedSearchCV

In [47]:
rlf = RandomizedSearchCV(clasiffier,param_distributions=parameters,n_iter=10,cv=5)

In [48]:
rlf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'lasticnet',
                                                    None),
                                        'solver': ('newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga')})

In [49]:
rlf.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 20}

In [50]:
classfiers = LogisticRegression(C=20, penalty='l2', solver='sag')

In [51]:
classfiers.fit(X_train,y_train)

LogisticRegression(C=20, solver='sag')

In [52]:
y_pred = classfiers.predict(X_test)

In [53]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



Hence Accuracy of the model is 100